//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouthFutureCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int Content_id { get; set; }
        public Nullable<int> Image_id { get; set; }
        public string ContentName { get; set; }
        public string ContentInfo { get; set; }
        public Nullable<int> File_id { get; set; }
        public int PageNum { get; set; }
    
        public virtual File File { get; set; }
        public virtual Image Image { get; set; }
    }
}
