//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouthFutureCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public int Donor_id { get; set; }
        public string DonorName { get; set; }
        public string DonorYear { get; set; }
        public string DonorLevel { get; set; }
        public string DonorStatus { get; set; }
    }
}
