//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouthFutureCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int ErrorLog_id { get; set; }
        public string ErrorDesc { get; set; }
        public System.DateTime ErrorDatetime { get; set; }
        public int User_id { get; set; }
    
        public virtual User User { get; set; }
    }
}
